name: Compilar y Publicar Release Automático

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Descargar el código fuente
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Instalar PyInstaller y dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Ejecutar script de compilacion y publicacion completa
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python github_build.py
